### ISSUE TITLE
Improve filter UI

### ISSUE THREAD

**Issue by sjavora** [lsocrate/rivalsdb#58]
First of all, thank you for creating and maintaining rivalsdb. It's been an invaluable resource!

One thing I seem to continually struggle with is the filters. This is what they look like when the database loads on my computer (and I presume this is standard for everybody):

<img width="816" alt="Screenshot 2024-06-21 at 9 06 26" src="https://github.com/RivalsDB/rivalsdb/assets/12349477/609f8d86-d1b5-44c0-8a61-388e643711f1">

It's a lot of tightly packed icons with the same size, color, with slightly larger spacings for sections. I'm not a newbie to the game and yet I still find myself taking a long time parsing all the icons every time I want to use the filters (and not just skip to the text box). I don't know how best to solve this, but one idea is to add a label for each section to make them stand out more.

Now, I'm not a designer or web developer, but I tried adding some divs in the web inspector to see what it could look like:

<img width="821" alt="Screenshot 2024-06-21 at 9 22 29" src="https://github.com/RivalsDB/rivalsdb/assets/12349477/5d49dc1d-b1fb-4fcf-9e15-1b0d1c3b7141">

(no idea what the sections in the first row would be named, that's why there's nothing there)

To me, this is instantly more usable. The centered text doesn't really work for narrow screens, but I'm sure that could be tweaked.

**Comment by Robsmash138** [comment]
Thanks @sjavora this is a great suggestion- I think our biggest issue is getting enough time to do updates like this, as this team is super small and this is volunteer work. However, would you maybe be interested in putting a PR together, and us reviewing it, then us putting it up? In other words- the quickest way to see this would be to contribute yourself. We have some other long standing issues people have asked for that we haven't been able to get to- so this probably wouldn't be the first one we would tackle- however if you were able to put up a PR and it looked workable, we would be willing to publish it. Thanks again for the suggestion.

**Comment by stopfstedt** [comment]
good idea. we already have these buttons grouped, but the markup needs to be tweaked. converting these groupings from `<div>` to `<fieldset>` / `<legend>` might be the way to go.

here a quick in-browser scratch-up:

![image](https://github.com/RivalsDB/rivalsdb/assets/1410427/84ed2106-c7ec-43b7-858e-bd172e80ca2a)

the legend and frame border seems a bit obnoxious, but can be muted with CSS. 

in any case, i'll have a stab at it over the weekend, will keep you posted.

**Comment by Robsmash138** [comment]
Committed- thanks for the suggestion @sjavora and thanks @stopfstedt for getting the fix in

**Comment by sjavora** [comment]
Thanks @Robsmash138 and @stopfstedt ! I did manage to eventually get a development environment set up for this project, but I was still pretty far from actually submitting a PR 😅
